[tool.poetry]
name = "sdk-python"
version = "0.1.0"
description = ""
authors = ["Mike Mann <mmann@peak6.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
